global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'mysql-cluster'
    static_configs:
      - targets: ['mysqld_exporter_node1:9104', 'mysqld_exporter_node2:9104', 'mysqld_exporter_node3:9104']