---
arch: "linux-amd64"
prometheus_version: "3.3.1"
node_exporter_version: "1.9.1"

prometheus_dir: "/opt/prometheus"
prometheus_config_dir: "/etc/prometheus"

node_exporter_dir: "/opt/node_exporter"

mysql_exporter_master_port: "9104"
mysql_exporter_slave_port: "9105"
