- name: Run Strapi CMS
  community.docker.docker_container:
    name: "{{ strapi_container_name }}"
    image: "{{ strapi_image }}"
    restart_policy: "{{ strapi_restart_policy }}"
    env:
      DATABASE_CLIENT: "{{ strapi_database_client }}"
      DATABASE_HOST: "{{ strapi_database_host }}"
      DATABASE_PORT: "{{ pg_port }}"
      DATABASE_NAME: "{{ pg_database }}"
      DATABASE_USERNAME: "{{ pg_username }}"
      DATABASE_PASSWORD: "{{ pg_password }}"
    ports:
      - "{{ strapi_ports }}"
    networks:
      - name: "{{ pg_network }}"
