---
- name: Connect to Patroni
  hosts: carrier

  tasks:
    - name: Run Strapi CMS
      community.docker.docker_container:
        name: "{{ strapi_container_name }}"
        image: "{{ strapi_image }}"
        restart_policy: "{{ default_restart_policy }}"
        recreate: true
        env:
          DATABASE_CLIENT: "{{ strapi_database_client }}"
          DATABASE_HOST: "{{ haproxy_container_name }}"
          DATABASE_PORT: "{{ pg_port }}"
          DATABASE_NAME: "{{ pg_database }}"
          DATABASE_USERNAME: "{{ pg_username }}"
          DATABASE_PASSWORD: "{{ pg_password }}"
        ports:
          - "{{ strapi_port_outside }}:1337"
        networks:
          - name: "{{ pg_network }}"

    - name: Waiting for Strapi to become available
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host }}:{{ strapi_port_outside }}"
        method: GET
        status_code: 200
      register: strapi_check
      retries: "{{ strapi_check_retries }}"
      delay: "{{ strapi_check_delay }}"
      until: strapi_check.status == 200

    - name: Confirm Strapi is live
      ansible.builtin.debug:
        msg: "Strapi is live at http://{{ hostvars[inventory_hostname].ansible_host }}:{{ strapi_port_outside }}"
